# Generated by Django 4.2.20 on 2025-06-23 02:22

from django.db import migrations

def fix_image_paths(apps, schema_editor):
    Book = apps.get_model('bookstore', 'Book')
    BookImage = apps.get_model('bookstore', 'BookImage')
    
    prefix_to_remove = 'media/'

    for book in Book.objects.all():
        if book.cover_image and book.cover_image.name.startswith(prefix_to_remove):
            book.cover_image.name = book.cover_image.name[len(prefix_to_remove):]
            book.save(update_fields=['cover_image'])

    for image in BookImage.objects.all():
        if image.image and image.image.name.startswith(prefix_to_remove):
            image.image.name = image.image.name[len(prefix_to_remove):]
            image.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_book_image_book_cover_image_alter_book_price_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_image_paths, migrations.RunPython.noop),
    ]
