# Generated by Django 4.2.20 on 2025-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_fix_image_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, help_text='Main cover image for the home page hero section', null=True, upload_to='site_settings/')),
                ('site_title', models.CharField(default='المكتبة الجيرمانية', help_text='Main site title displayed across the website', max_length=200)),
                ('hero_title', models.CharField(default='اكتشف كتابك القادم المثالي', help_text='Main headline on the home page hero section', max_length=300)),
                ('hero_subtitle', models.TextField(default='مجموعة منتقاة من أفضل الكتب لتعلم اللغة الألمانية وتطوير مهارات القراءة', help_text='Subtitle text on the home page hero section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
